apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: hasura
  namespace: graphql
  annotations:
    apisix.apache.org/timeout: "950"
    apisix.apache.org/websocket: "true"
spec:
  ingressClassName: apisix
  http:
    - name: hasura
      websocket: true
      match:
        hosts:
          - "graphql.app.suncoast.systems"
        paths: ["/v1/graphql", "/v1/graphql/*"]
      backends:
        - serviceName: hasura
          servicePort: 8080
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins_by_regex:
              - "^https://([a-zA-Z0-9-]+\\.)*graphql\\.app\\.suncoast\\.systems$"
            allow_origins: "https://graphql.app.suncoast.systems"
            allow_methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
            allow_headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With,Cache-Control,Pragma,User-Agent,X-Real-IP,X-Forwarded-For,X-Client-IP,X-Original-Forwarded-For,traceparent,tracestate,baggage,X-Traceparent,X-Tracestate,X-Baggage"
            allow_credential: true
            max_age: 86400
        - name: real-ip
          enable: true
          config:
            source: X-Forwarded-For
            recursive: true
            trusted_addresses:
              - 127.0.0.1
              - 10.0.0.0/24
              - 10.0.0.10/32
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
        - name: proxy-rewrite
          enable: true
          config:
            headers:
              X-Forwarded-For: "$proxy_add_x_forwarded_for"
              X-Real-IP: "$remote_addr"
              X-Client-IP: "$remote_addr"
              X-Original-Forwarded-For: "$http_x_forwarded_for"
              X-Forwarded-Proto: "$scheme"
              X-Forwarded-Host: "$host"
              Traceparent: "$opentelemetry_context_traceparent"
              Tracestate: "$http_tracestate"
              Baggage: "$http_baggage"
              X-Traceparent: "$opentelemetry_context_traceparent"
              X-Tracestate: "$http_tracestate"
              X-Baggage: "$http_baggage"
              X-Hasura-Traceparent: "$opentelemetry_context_traceparent"
              X-Hasura-Tracestate: "$http_tracestate"
              X-Hasura-Baggage: "$http_baggage"
              X-Forwarded-Traceparent: "$opentelemetry_context_traceparent"
              X-Forwarded-Tracestate: "$http_tracestate"
              X-Forwarded-Baggage: "$http_baggage"
