apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: graphql
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-store-graphql
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: value
      remoteRef:
        # Vault KVv2 path: secret/data/graphql/cloudflare-tunnel-token
        key: graphql/cloudflare-tunnel-token
        property: value
