apiVersion: v1
kind: Namespace
metadata:
  name: graphql
  labels:
    app: graphql
  annotations:
    linkerd.io/inject: enabled
    field.cattle.io/projectId: local:infrastructure
    vault.hashicorp.com/agent-injection: enabled
