apiVersion: v1
kind: Namespace
metadata:
  name: graphql
  labels:
    app: graphql
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-cpu-request: "25m"
    config.linkerd.io/proxy-memory-request: "64Mi"
    field.cattle.io/projectId: local:infrastructure
    vault.hashicorp.com/agent-injection: enabled
