apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store-openobserve
  namespace: openobserve
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: externalsecrets-openobserve
          serviceAccountRef:
            name: openobserve-cloudflare-tunnel-external-secrets
